<?php

declare(strict_types=1);
use Heart\Character\Domain\Entities\LevelEntity;

beforeEach(function (): void {
    // TODO: Change the autogenerated stub
});
test('level entity', function (): void {
    new LevelEntity(1);

    //        foreach (range(0, 11) as $months) {
    //            foreach (range(0, 30) as $days) {
    //                foreach (range(0, 20) as $qtdMensagem) {
    //                    $generatedExperience = $levelEntity->generateVoiceExperience(
    //                        VoiceStatesEnum::Muted,
    //                        true
    //                    );
    //
    //                    dump('exp ganha:' . $generatedExperience);
    //                    dump('level atual: ' . $levelEntity->getLevel());
    //                    dump('level exp atual: ' . $levelEntity->getLevelUpStatus());
    //                }
    //            }
    //        }
    expect(true)->toBeTrue();
});
